"""The three ``(V, G)`` profiles used in the paper.

Each function evaluates a potential/gain-loss pair on a grid ``x`` produced by
:func:`nhvk.core.make_grid` and returns ``(V, G)``.  The gain-loss profile is
returned with its physical amplitude already applied, so a :class:`nhvk.core.Model`
built from these arrays is used at ``eps = 1``; passing the unit amplitude and
continuing in ``eps`` from ``0`` to ``A`` is the equivalent route taken by the
scripts that need a Hermitian anchor.
"""

from __future__ import annotations

import numpy as np

__all__ = ["wadati_gaussian", "pt_well", "pt_barrier"]


def wadati_gaussian(x: np.ndarray, A: float) -> tuple[np.ndarray, np.ndarray]:
    """Theorem A profile: the Wadati pair generated by ``g = A x exp(-x^2/2)``.

    Returns ``V = -g^2`` and ``G = g' = A (1 - x^2) exp(-x^2/2)``, so that the
    linear part is Wadati-factorisable,
    ``-d_xx - g^2 + i g' = (d_x + i g)(-d_x + i g)``.

    Two properties of ``g`` matter for the paper's construction.  ``g`` is
    **odd**, so ``G = g'`` is **even**; since a PT-symmetric configuration needs
    ``G`` odd, this branch is genuinely non-PT-symmetric, which is the point of
    Theorem A.  And ``g`` is **non-monotone**, so ``G`` changes sign -- Lemma P
    forbids a sign-definite ``G``, because any decaying stationary state must
    satisfy ``int G |phi|^2 dx = 0``.

    Parameters
    ----------
    x : ndarray
        Grid points.
    A : float
        Amplitude of ``g``.  The paper uses ``A = 1``.

    Returns
    -------
    V, G : ndarray
        Potential and gain-loss profile on ``x``.
    """
    g = A*x*np.exp(-x**2/2)
    gp = A*(1-x**2)*np.exp(-x**2/2)
    return -g**2, gp


def pt_well(x: np.ndarray, V0: float, A: float) -> tuple[np.ndarray, np.ndarray]:
    """Appendix F Configuration I: PT-symmetric sech-squared well.

    Returns ``V = -V0 sech^2(x)`` (even) and ``G = A sech(x) tanh(x)`` (odd), so
    the configuration is PT-symmetric.  The paper uses ``V0 = 2``, for which the
    linear operator ``-d_xx - 2 sech^2(x)`` has its bound state at ``E = -1`` and
    the focusing soliton family lives at ``omega < -1``.

    Parameters
    ----------
    x : ndarray
        Grid points.
    V0 : float
        Depth of the well.
    A : float
        Amplitude of the gain-loss profile.

    Returns
    -------
    V, G : ndarray
        Potential and gain-loss profile on ``x``.
    """
    V = -V0/np.cosh(x)**2
    G = A*np.tanh(x)/np.cosh(x)
    return V, G


def pt_barrier(x: np.ndarray, V0: float, A: float) -> tuple[np.ndarray, np.ndarray]:
    """Sections 3.7 and 5.3: PT-symmetric sech-squared barrier.

    Returns ``V = +V0 sech^2(x)`` (even) and ``G = -A sech(x) tanh(x)`` (odd).
    The paper uses ``V0 = 0.3``.

    Note that ``V`` here is a **repulsive barrier**, not a well: the linear
    operator ``-d_xx + V0 sech^2(x)`` has no bound state, so there is no linear
    eigenvalue to bifurcate from and the focusing soliton family exists for all
    ``omega < 0``.  That is what makes this base usable at frequencies as far
    apart as ``omega = -0.8`` and ``omega = -2.5``.

    Parameters
    ----------
    x : ndarray
        Grid points.
    V0 : float
        Height of the barrier.
    A : float
        Amplitude of the gain-loss profile.

    Returns
    -------
    V, G : ndarray
        Potential and gain-loss profile on ``x``.
    """
    V = V0/np.cosh(x)**2
    G = -A*np.tanh(x)/np.cosh(x)
    return V, G
